on:
  push:
    branches:
      - main
  pull_request:

name: CI

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: make deps
      - run: make lint
      - run: make typecheck
      - run: make test
      - run: make build
      - run: git add --intent-to-add . && git diff --exit-code --stat
